version: '3'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: schnitzelhoelle
      MARIADB_PASSWORD: schnitzelhoelle
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
