
spring:
  main:
    banner-mode: "off"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/schnitzelhoelle
    username: schnitzelhoelle
    password: schnitzelhoelle
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: "/api"
  security:
    user:
      name: "paul"
      password: "tiger"
      roles:
      - user
      - manager
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE